In [1]:
import pandas as pd

In [2]:
CCTV_Seoul = pd.read_csv('CCTV_in_Seoul.csv',encoding = 'utf-8')
CCTV_Seoul.head()

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  3238       1292    430    584    932
1  강동구  1010        379     99    155    377
2  강북구   831        369    120    138    204
3  강서구   911        388    258    184     81
4  관악구  2109        846    260    390    613

In [3]:
CCTV_Seoul.columns

Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

In [10]:
CCTV_Seoul.columns[0]

'기관명'

In [11]:
CCTV_Seoul.rename(columns={CCTV_Seoul.columns[0]:'구별'}, inplace=True)

In [13]:
CCTV_Seoul.head()

    구별    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  3238       1292    430    584    932
1  강동구  1010        379     99    155    377
2  강북구   831        369    120    138    204
3  강서구   911        388    258    184     81
4  관악구  2109        846    260    390    613

In [15]:
Population_in_Seoul = pd.read_excel('Population_in_Seoul.xls',encoding = 'utf-8')
Population_in_Seoul.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2018,합계,4263868,10049607,4910849,5138758,9765623,4773899,4991724,283984,136950,147034,2.29,1416131
3,2018,종로구,73735,163026,79156,83870,153065,74825,78240,9961,4331,5630,2.08,26742
4,2018,중구,61502,135633,66674,68959,125725,61947,63778,9908,4727,5181,2.04,22005

In [16]:
Population_in_Seoul = pd.read_excel('Population_in_Seoul.xls',header = 2,parse_cols='B,D,G,J,N',encoding = 'utf-8')
Population_in_Seoul.head()

c:\users\gus26\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: the 'parse_cols' keyword is deprecated, use 'usecols' instead
  """Entry point for launching an IPython kernel.

   자치구         계      계.1     계.2  65세이상고령자
0   합계  10049607  9765623  283984   1416131
1  종로구    163026   153065    9961     26742
2   중구    135633   125725    9908     22005
3  용산구    245090   228999   16091     37640
4  성동구    316463   308221    8242     42767

In [18]:
Population_in_Seoul.rename(columns = {Population_in_Seoul.columns[0]:'구별',
                                      Population_in_Seoul.columns[1]:'인구수',
                                      Population_in_Seoul.columns[2]:'한국인',
                                      Population_in_Seoul.columns[3]:'외국인',
                                      Population_in_Seoul.columns[4]:'고령자'}, inplace = True)
Population_in_Seoul.head()

    구별       인구수      한국인     외국인      고령자
0   합계  10049607  9765623  283984  1416131
1  종로구    163026   153065    9961    26742
2   중구    135633   125725    9908    22005
3  용산구    245090   228999   16091    37640
4  성동구    316463   308221    8242    42767

In [22]:
CCTV_Seoul.head()

    구별    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  3238       1292    430    584    932
1  강동구  1010        379     99    155    377
2  강북구   831        369    120    138    204
3  강서구   911        388    258    184     81
4  관악구  2109        846    260    390    613

In [23]:
CCTV_Seoul.sort_values(by='소계',ascending = False)

      구별    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  3238       1292    430    584    932
18   양천구  2482       1843    142     30    467
14   서초구  2297       1406    157    336    398
4    관악구  2109        846    260    390    613
21   은평구  2108       1138    224    278    468
20   용산구  2096       1368    218    112    398
6    구로구  1884       1142    173    246    323
10  동대문구  1870       1070     23    198    579
16   성북구  1651       1009     78    360    204
22   종로구  1619        464    314    211    630
8    노원구  1566        542     57    451    516
7    금천구  1348        674     51    269    354
15   성동구  1327        730     91    241    265
11   동작구  1302        544    341    103    314
19  영등포구  1277        495    214    195    373
13  서대문구  1254        844     50     68    292
17   송파구  1081        529     21     68    463
23    중구  1023        413    190     72    348
1    강동구  1010        379     99    155    377
12   마포구   980        314    118    169    379
24   중랑구   916        509    121    177    109
3    강서구   911        388    258    184     81
5    광진구   878        573     78     53    174
2    강북구   831        369    120    138    204
9    도봉구   825        238    159     42    386

In [30]:
CCTV_Seoul['최근 증가율'] = ( CCTV_Seoul['2016년'] + CCTV_Seoul['2015년'] + CCTV_Seoul['2014년'] ) / CCTV_Seoul['2013년도 이전']*100
CCTV_Seoul.sort_values(by = '최근 증가율', ascending = False)

      구별    소계  2013년도 이전  2014년  2015년  2016년      최근 증가율
22   종로구  1619        464    314    211    630  248.922414
9    도봉구   825        238    159     42    386  246.638655
12   마포구   980        314    118    169    379  212.101911
8    노원구  1566        542     57    451    516  188.929889
1    강동구  1010        379     99    155    377  166.490765
19  영등포구  1277        495    214    195    373  157.979798
0    강남구  3238       1292    430    584    932  150.619195
4    관악구  2109        846    260    390    613  149.290780
23    중구  1023        413    190     72    348  147.699758
11   동작구  1302        544    341    103    314  139.338235
3    강서구   911        388    258    184     81  134.793814
2    강북구   831        369    120    138    204  125.203252
17   송파구  1081        529     21     68    463  104.347826
7    금천구  1348        674     51    269    354  100.000000
21   은평구  2108       1138    224    278    468   85.237258
15   성동구  1327        730     91    241    265   81.780822
24   중랑구   916        509    121    177    109   79.960707
10  동대문구  1870       1070     23    198    579   74.766355
6    구로구  1884       1142    173    246    323   64.973730
16   성북구  1651       1009     78    360    204   63.627354
14   서초구  2297       1406    157    336    398   63.371266
5    광진구   878        573     78     53    174   53.228621
20   용산구  2096       1368    218    112    398   53.216374
13  서대문구  1254        844     50     68    292   48.578199
18   양천구  2482       1843    142     30    467   34.671731

In [32]:
Population_in_Seoul

      구별       인구수      한국인     외국인      고령자
0     합계  10049607  9765623  283984  1416131
1    종로구    163026   153065    9961    26742
2     중구    135633   125725    9908    22005
3    용산구    245090   228999   16091    37640
4    성동구    316463   308221    8242    42767
5    광진구    371063   355559   15504    45619
6   동대문구    364338   348052   16286    57165
7    중랑구    408147   403209    4938    61830
8    성북구    447687   435868   11819    67782
9    강북구    322915   319164    3751    58196
10   도봉구    341649   339413    2236    55964
11   노원구    548160   543752    4408    77096
12   은평구    487666   483197    4469    77420
13  서대문구    323080   310313   12767    50456
14   마포구    386359   375077   11282    50833
15   양천구    468145   464185    3960    58045
16   강서구    603611   596949    6662    79660
17   구로구    438486   404497   33989    61801
18   금천구    254021   233917   20104    35739
19  영등포구    403600   367778   35822    55673
20   동작구    409385   396203   13182    59479
21   관악구    520040   501957   18083    72249
22   서초구    438163   433951    4212    54751
23   강남구    547453   542364    5089    67085
24   송파구    673507   666635    6872    81364
25   강동구    431920   427573    4347    58770

In [44]:
Population_in_Seoul = Population_in_Seoul.drop([0],inplace =False)

In [45]:
Population_in_Seoul['구별'].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구'], dtype=object)

In [46]:
Population_in_Seoul['외국인비율'] = Population_in_Seoul['외국인'] / Population_in_Seoul['인구수'] * 100
Population_in_Seoul['고령자비율'] = Population_in_Seoul['고령자'] / Population_in_Seoul['인구수'] * 100
Population_in_Seoul

      구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
1    종로구  163026  153065   9961  26742  6.110068  16.403518
2     중구  135633  125725   9908  22005  7.305007  16.223928
3    용산구  245090  228999  16091  37640  6.565343  15.357624
4    성동구  316463  308221   8242  42767  2.604412  13.514060
5    광진구  371063  355559  15504  45619  4.178266  12.294139
6   동대문구  364338  348052  16286  57165  4.470025  15.690101
7    중랑구  408147  403209   4938  61830  1.209858  15.148954
8    성북구  447687  435868  11819  67782  2.640014  15.140489
9    강북구  322915  319164   3751  58196  1.161606  18.022080
10   도봉구  341649  339413   2236  55964  0.654473  16.380554
11   노원구  548160  543752   4408  77096  0.804145  14.064507
12   은평구  487666  483197   4469  77420  0.916406  15.875620
13  서대문구  323080  310313  12767  50456  3.951653  15.617185
14   마포구  386359  375077  11282  50833  2.920082  13.156934
15   양천구  468145  464185   3960  58045  0.845892  12.398936
16   강서구  603611  596949   6662  79660  1.103691  13.197241
17   구로구  438486  404497  33989  61801  7.751445  14.094179
18   금천구  254021  233917  20104  35739  7.914306  14.069309
19  영등포구  403600  367778  35822  55673  8.875619  13.794103
20   동작구  409385  396203  13182  59479  3.219952  14.528866
21   관악구  520040  501957  18083  72249  3.477233  13.892970
22   서초구  438163  433951   4212  54751  0.961286  12.495578
23   강남구  547453  542364   5089  67085  0.929578  12.254020
24   송파구  673507  666635   6872  81364  1.020331  12.080647
25   강동구  431920  427573   4347  58770  1.006436  13.606686

In [47]:
Population_in_Seoul.sort_values(by = '인구수',ascending = False)

      구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
24   송파구  673507  666635   6872  81364  1.020331  12.080647
16   강서구  603611  596949   6662  79660  1.103691  13.197241
11   노원구  548160  543752   4408  77096  0.804145  14.064507
23   강남구  547453  542364   5089  67085  0.929578  12.254020
21   관악구  520040  501957  18083  72249  3.477233  13.892970
12   은평구  487666  483197   4469  77420  0.916406  15.875620
15   양천구  468145  464185   3960  58045  0.845892  12.398936
8    성북구  447687  435868  11819  67782  2.640014  15.140489
17   구로구  438486  404497  33989  61801  7.751445  14.094179
22   서초구  438163  433951   4212  54751  0.961286  12.495578
25   강동구  431920  427573   4347  58770  1.006436  13.606686
20   동작구  409385  396203  13182  59479  3.219952  14.528866
7    중랑구  408147  403209   4938  61830  1.209858  15.148954
19  영등포구  403600  367778  35822  55673  8.875619  13.794103
14   마포구  386359  375077  11282  50833  2.920082  13.156934
5    광진구  371063  355559  15504  45619  4.178266  12.294139
6   동대문구  364338  348052  16286  57165  4.470025  15.690101
10   도봉구  341649  339413   2236  55964  0.654473  16.380554
13  서대문구  323080  310313  12767  50456  3.951653  15.617185
9    강북구  322915  319164   3751  58196  1.161606  18.022080
4    성동구  316463  308221   8242  42767  2.604412  13.514060
18   금천구  254021  233917  20104  35739  7.914306  14.069309
3    용산구  245090  228999  16091  37640  6.565343  15.357624
1    종로구  163026  153065   9961  26742  6.110068  16.403518
2     중구  135633  125725   9908  22005  7.305007  16.223928

In [48]:
Population_in_Seoul.sort_values(by = '외국인',ascending = False)

      구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
19  영등포구  403600  367778  35822  55673  8.875619  13.794103
17   구로구  438486  404497  33989  61801  7.751445  14.094179
18   금천구  254021  233917  20104  35739  7.914306  14.069309
21   관악구  520040  501957  18083  72249  3.477233  13.892970
6   동대문구  364338  348052  16286  57165  4.470025  15.690101
3    용산구  245090  228999  16091  37640  6.565343  15.357624
5    광진구  371063  355559  15504  45619  4.178266  12.294139
20   동작구  409385  396203  13182  59479  3.219952  14.528866
13  서대문구  323080  310313  12767  50456  3.951653  15.617185
8    성북구  447687  435868  11819  67782  2.640014  15.140489
14   마포구  386359  375077  11282  50833  2.920082  13.156934
1    종로구  163026  153065   9961  26742  6.110068  16.403518
2     중구  135633  125725   9908  22005  7.305007  16.223928
4    성동구  316463  308221   8242  42767  2.604412  13.514060
24   송파구  673507  666635   6872  81364  1.020331  12.080647
16   강서구  603611  596949   6662  79660  1.103691  13.197241
23   강남구  547453  542364   5089  67085  0.929578  12.254020
7    중랑구  408147  403209   4938  61830  1.209858  15.148954
12   은평구  487666  483197   4469  77420  0.916406  15.875620
11   노원구  548160  543752   4408  77096  0.804145  14.064507
25   강동구  431920  427573   4347  58770  1.006436  13.606686
22   서초구  438163  433951   4212  54751  0.961286  12.495578
15   양천구  468145  464185   3960  58045  0.845892  12.398936
9    강북구  322915  319164   3751  58196  1.161606  18.022080
10   도봉구  341649  339413   2236  55964  0.654473  16.380554

In [49]:
Population_in_Seoul.sort_values(by = '외국인비율',ascending = False)

      구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
19  영등포구  403600  367778  35822  55673  8.875619  13.794103
18   금천구  254021  233917  20104  35739  7.914306  14.069309
17   구로구  438486  404497  33989  61801  7.751445  14.094179
2     중구  135633  125725   9908  22005  7.305007  16.223928
3    용산구  245090  228999  16091  37640  6.565343  15.357624
1    종로구  163026  153065   9961  26742  6.110068  16.403518
6   동대문구  364338  348052  16286  57165  4.470025  15.690101
5    광진구  371063  355559  15504  45619  4.178266  12.294139
13  서대문구  323080  310313  12767  50456  3.951653  15.617185
21   관악구  520040  501957  18083  72249  3.477233  13.892970
20   동작구  409385  396203  13182  59479  3.219952  14.528866
14   마포구  386359  375077  11282  50833  2.920082  13.156934
8    성북구  447687  435868  11819  67782  2.640014  15.140489
4    성동구  316463  308221   8242  42767  2.604412  13.514060
7    중랑구  408147  403209   4938  61830  1.209858  15.148954
9    강북구  322915  319164   3751  58196  1.161606  18.022080
16   강서구  603611  596949   6662  79660  1.103691  13.197241
24   송파구  673507  666635   6872  81364  1.020331  12.080647
25   강동구  431920  427573   4347  58770  1.006436  13.606686
22   서초구  438163  433951   4212  54751  0.961286  12.495578
23   강남구  547453  542364   5089  67085  0.929578  12.254020
12   은평구  487666  483197   4469  77420  0.916406  15.875620
15   양천구  468145  464185   3960  58045  0.845892  12.398936
11   노원구  548160  543752   4408  77096  0.804145  14.064507
10   도봉구  341649  339413   2236  55964  0.654473  16.380554

In [50]:
Population_in_Seoul.sort_values(by = '고령자',ascending = False)

      구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
24   송파구  673507  666635   6872  81364  1.020331  12.080647
16   강서구  603611  596949   6662  79660  1.103691  13.197241
12   은평구  487666  483197   4469  77420  0.916406  15.875620
11   노원구  548160  543752   4408  77096  0.804145  14.064507
21   관악구  520040  501957  18083  72249  3.477233  13.892970
8    성북구  447687  435868  11819  67782  2.640014  15.140489
23   강남구  547453  542364   5089  67085  0.929578  12.254020
7    중랑구  408147  403209   4938  61830  1.209858  15.148954
17   구로구  438486  404497  33989  61801  7.751445  14.094179
20   동작구  409385  396203  13182  59479  3.219952  14.528866
25   강동구  431920  427573   4347  58770  1.006436  13.606686
9    강북구  322915  319164   3751  58196  1.161606  18.022080
15   양천구  468145  464185   3960  58045  0.845892  12.398936
6   동대문구  364338  348052  16286  57165  4.470025  15.690101
10   도봉구  341649  339413   2236  55964  0.654473  16.380554
19  영등포구  403600  367778  35822  55673  8.875619  13.794103
22   서초구  438163  433951   4212  54751  0.961286  12.495578
14   마포구  386359  375077  11282  50833  2.920082  13.156934
13  서대문구  323080  310313  12767  50456  3.951653  15.617185
5    광진구  371063  355559  15504  45619  4.178266  12.294139
4    성동구  316463  308221   8242  42767  2.604412  13.514060
3    용산구  245090  228999  16091  37640  6.565343  15.357624
18   금천구  254021  233917  20104  35739  7.914306  14.069309
1    종로구  163026  153065   9961  26742  6.110068  16.403518
2     중구  135633  125725   9908  22005  7.305007  16.223928

In [43]:
Population_in_Seoul.sort_values(by = '고령자비율',ascending = False)

      구별       인구수      한국인     외국인      고령자     외국인비율      고령자비율
9    강북구    322915   319164    3751    58196  1.161606  18.022080
1    종로구    163026   153065    9961    26742  6.110068  16.403518
10   도봉구    341649   339413    2236    55964  0.654473  16.380554
2     중구    135633   125725    9908    22005  7.305007  16.223928
12   은평구    487666   483197    4469    77420  0.916406  15.875620
6   동대문구    364338   348052   16286    57165  4.470025  15.690101
13  서대문구    323080   310313   12767    50456  3.951653  15.617185
3    용산구    245090   228999   16091    37640  6.565343  15.357624
7    중랑구    408147   403209    4938    61830  1.209858  15.148954
8    성북구    447687   435868   11819    67782  2.640014  15.140489
20   동작구    409385   396203   13182    59479  3.219952  14.528866
17   구로구    438486   404497   33989    61801  7.751445  14.094179
0     합계  10049607  9765623  283984  1416131  2.825822  14.091407
18   금천구    254021   233917   20104    35739  7.914306  14.069309
11   노원구    548160   543752    4408    77096  0.804145  14.064507
21   관악구    520040   501957   18083    72249  3.477233  13.892970
19  영등포구    403600   367778   35822    55673  8.875619  13.794103
25   강동구    431920   427573    4347    58770  1.006436  13.606686
4    성동구    316463   308221    8242    42767  2.604412  13.514060
16   강서구    603611   596949    6662    79660  1.103691  13.197241
14   마포구    386359   375077   11282    50833  2.920082  13.156934
22   서초구    438163   433951    4212    54751  0.961286  12.495578
15   양천구    468145   464185    3960    58045  0.845892  12.398936
5    광진구    371063   355559   15504    45619  4.178266  12.294139
23   강남구    547453   542364    5089    67085  0.929578  12.254020
24   송파구    673507   666635    6872    81364  1.020331  12.080647

In [56]:
data_result = pd.merge(CCTV_Seoul,Population_in_Seoul, on='구별')
data_result

,구별,소계,2013년도 이전,2014년,2015년,2016년,최근 증가율,인구수,한국인,외국인,고령자,외국인비율,고령자비율
0,강남구,3238,1292,430,584,932,150.619195,547453,542364,5089,67085,0.929578,12.254020
1,강동구,1010,379,99,155,377,166.490765,431920,427573,4347,58770,1.006436,13.606686
2,강북구,831,369,120,138,204,125.203252,322915,319164,3751,58196,1.161606,18.022080
3,강서구,911,388,258,184,81,134.793814,603611,596949,6662,79660,1.103691,13.197241
4,관악구,2109,846,260,390,613,149.290780,520040,501957,18083,72249,3.477233,13.892970
5,광진구,878,573,78,53,174,53.228621,371063,355559,15504,45619,4.178266,12.294139
6,구로구,1884,1142,173,246,323,64.973730,438486,404497,33989,61801,7.751445,14.094179
7,금천구,1348,674,51,269,354,100.000000,254021,233917,20104,35739,7.914306,14.069309
8,노원구,1566,542,57,451,516,188.929889,548160,543752,4408,77096,0.804145,14.064507
9,도봉구,825,238,159,42,386,246.638655,341649,339413,2236,55964,0.654473,16.380554
10,동대문구,1870,1070,23,198,579,74.766355,364338,348052,16286,57165,4.470025,15.690101
11,동작구,1302,544,341,103,314,139.338235,409385,396203,13182,59479,3.219952,14.528866
12,마포구,980,314,118,169,379,212.101911,386359,375077,11282,50833,2.920082,13.156934
13,서대문구,1254,844,50,68,292,48.578199,323080,310313,12767,50456,3.951653,15.617185
14,서초구,2297,1406,157,336,398,63.371266,438163,433951,4212,54751,0.961286,12.495578
15,성동구,1327,730,91,241,265,81.780822,316463,308221,8242,42767,2.604412,13.514060
16,성북구,1651,1009,78,360,204,63.627354,447687,435868,11819,67782,2.640014,15.140489
17,송파구,1081,529,21,68,463,104.347826,673507,666635,6872,81364,1.020331,12.080647
18,양천구,2482,1843,142,30,467,34.671731,468145,464185,3960,58045,0.845892,12.398936
19,영등포구,1277,495,214,195,373,157.979798,403600,367778,35822,55673,8.875619,13.794103
20,용산구,2096,1368,218,112,398,53.216374,245090,228999,16091,37640,6.565343,15.357624
21,은평구,2108,1138,224,278,468,85.237258,487666,483197,4469,77420,0.916406,15.875620
22,종로구,1619,464,314,211,630,248.922414,163026,153065,9961,26742,6.110068,16.403518
23,중구,1023,413,190,72,348,147.699758,135633,125725,9908,22005,7.305007,16.223928
24,중랑구,916,509,121,177,109,79.960707,408147,403209,4938,61830,1.209858,15.148954

In [58]:
del data_result['2013년도 이전']
del data_result['2014년']
del data_result['2015년']
del data_result['2016년']
data_result

      구별    소계      최근 증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율
0    강남구  3238  150.619195  547453  542364   5089  67085  0.929578  12.254020
1    강동구  1010  166.490765  431920  427573   4347  58770  1.006436  13.606686
2    강북구   831  125.203252  322915  319164   3751  58196  1.161606  18.022080
3    강서구   911  134.793814  603611  596949   6662  79660  1.103691  13.197241
4    관악구  2109  149.290780  520040  501957  18083  72249  3.477233  13.892970
5    광진구   878   53.228621  371063  355559  15504  45619  4.178266  12.294139
6    구로구  1884   64.973730  438486  404497  33989  61801  7.751445  14.094179
7    금천구  1348  100.000000  254021  233917  20104  35739  7.914306  14.069309
8    노원구  1566  188.929889  548160  543752   4408  77096  0.804145  14.064507
9    도봉구   825  246.638655  341649  339413   2236  55964  0.654473  16.380554
10  동대문구  1870   74.766355  364338  348052  16286  57165  4.470025  15.690101
11   동작구  1302  139.338235  409385  396203  13182  59479  3.219952  14.528866
12   마포구   980  212.101911  386359  375077  11282  50833  2.920082  13.156934
13  서대문구  1254   48.578199  323080  310313  12767  50456  3.951653  15.617185
14   서초구  2297   63.371266  438163  433951   4212  54751  0.961286  12.495578
15   성동구  1327   81.780822  316463  308221   8242  42767  2.604412  13.514060
16   성북구  1651   63.627354  447687  435868  11819  67782  2.640014  15.140489
17   송파구  1081  104.347826  673507  666635   6872  81364  1.020331  12.080647
18   양천구  2482   34.671731  468145  464185   3960  58045  0.845892  12.398936
19  영등포구  1277  157.979798  403600  367778  35822  55673  8.875619  13.794103
20   용산구  2096   53.216374  245090  228999  16091  37640  6.565343  15.357624
21   은평구  2108   85.237258  487666  483197   4469  77420  0.916406  15.875620
22   종로구  1619  248.922414  163026  153065   9961  26742  6.110068  16.403518
23    중구  1023  147.699758  135633  125725   9908  22005  7.305007  16.223928
24   중랑구   916   79.960707  408147  403209   4938  61830  1.209858  15.148954

In [60]:
data_result.set_index('구별')

        소계      최근 증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율
구별
강남구   3238  150.619195  547453  542364   5089  67085  0.929578  12.254020
강동구   1010  166.490765  431920  427573   4347  58770  1.006436  13.606686
강북구    831  125.203252  322915  319164   3751  58196  1.161606  18.022080
강서구    911  134.793814  603611  596949   6662  79660  1.103691  13.197241
관악구   2109  149.290780  520040  501957  18083  72249  3.477233  13.892970
광진구    878   53.228621  371063  355559  15504  45619  4.178266  12.294139
구로구   1884   64.973730  438486  404497  33989  61801  7.751445  14.094179
금천구   1348  100.000000  254021  233917  20104  35739  7.914306  14.069309
노원구   1566  188.929889  548160  543752   4408  77096  0.804145  14.064507
도봉구    825  246.638655  341649  339413   2236  55964  0.654473  16.380554
동대문구  1870   74.766355  364338  348052  16286  57165  4.470025  15.690101
동작구   1302  139.338235  409385  396203  13182  59479  3.219952  14.528866
마포구    980  212.101911  386359  375077  11282  50833  2.920082  13.156934
서대문구  1254   48.578199  323080  310313  12767  50456  3.951653  15.617185
서초구   2297   63.371266  438163  433951   4212  54751  0.961286  12.495578
성동구   1327   81.780822  316463  308221   8242  42767  2.604412  13.514060
성북구   1651   63.627354  447687  435868  11819  67782  2.640014  15.140489
송파구   1081  104.347826  673507  666635   6872  81364  1.020331  12.080647
양천구   2482   34.671731  468145  464185   3960  58045  0.845892  12.398936
영등포구  1277  157.979798  403600  367778  35822  55673  8.875619  13.794103
용산구   2096   53.216374  245090  228999  16091  37640  6.565343  15.357624
은평구   2108   85.237258  487666  483197   4469  77420  0.916406  15.875620
종로구   1619  248.922414  163026  153065   9961  26742  6.110068  16.403518
중구    1023  147.699758  135633  125725   9908  22005  7.305007  16.223928
중랑구    916   79.960707  408147  403209   4938  61830  1.209858  15.148954

In [62]:
import numpy as np

In [63]:
np.corrcoef(data_result['고령자비율'],data_result['소계'])

array([[ 1.        , -0.27474224],
       [-0.27474224,  1.        ]])

In [64]:
np.corrcoef(data_result['외국인비율'],data_result['소계'])

array([[ 1.        , -0.05057013],
       [-0.05057013,  1.        ]])

In [65]:
np.corrcoef(data_result['인구수'],data_result['소계'])

array([[1.        , 0.22152789],
       [0.22152789, 1.        ]])

In [67]:
data_result.sort_values(by='인구수',ascending = False)

      구별    소계      최근 증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율
17   송파구  1081  104.347826  673507  666635   6872  81364  1.020331  12.080647
3    강서구   911  134.793814  603611  596949   6662  79660  1.103691  13.197241
8    노원구  1566  188.929889  548160  543752   4408  77096  0.804145  14.064507
0    강남구  3238  150.619195  547453  542364   5089  67085  0.929578  12.254020
4    관악구  2109  149.290780  520040  501957  18083  72249  3.477233  13.892970
21   은평구  2108   85.237258  487666  483197   4469  77420  0.916406  15.875620
18   양천구  2482   34.671731  468145  464185   3960  58045  0.845892  12.398936
16   성북구  1651   63.627354  447687  435868  11819  67782  2.640014  15.140489
6    구로구  1884   64.973730  438486  404497  33989  61801  7.751445  14.094179
14   서초구  2297   63.371266  438163  433951   4212  54751  0.961286  12.495578
1    강동구  1010  166.490765  431920  427573   4347  58770  1.006436  13.606686
11   동작구  1302  139.338235  409385  396203  13182  59479  3.219952  14.528866
24   중랑구   916   79.960707  408147  403209   4938  61830  1.209858  15.148954
19  영등포구  1277  157.979798  403600  367778  35822  55673  8.875619  13.794103
12   마포구   980  212.101911  386359  375077  11282  50833  2.920082  13.156934
5    광진구   878   53.228621  371063  355559  15504  45619  4.178266  12.294139
10  동대문구  1870   74.766355  364338  348052  16286  57165  4.470025  15.690101
9    도봉구   825  246.638655  341649  339413   2236  55964  0.654473  16.380554
13  서대문구  1254   48.578199  323080  310313  12767  50456  3.951653  15.617185
2    강북구   831  125.203252  322915  319164   3751  58196  1.161606  18.022080
15   성동구  1327   81.780822  316463  308221   8242  42767  2.604412  13.514060
7    금천구  1348  100.000000  254021  233917  20104  35739  7.914306  14.069309
20   용산구  2096   53.216374  245090  228999  16091  37640  6.565343  15.357624
22   종로구  1619  248.922414  163026  153065   9961  26742  6.110068  16.403518
23    중구  1023  147.699758  135633  125725   9908  22005  7.305007  16.223928

In [68]:
data_result.sort_values(by='소계',ascending = False)

      구별    소계      최근 증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율
0    강남구  3238  150.619195  547453  542364   5089  67085  0.929578  12.254020
18   양천구  2482   34.671731  468145  464185   3960  58045  0.845892  12.398936
14   서초구  2297   63.371266  438163  433951   4212  54751  0.961286  12.495578
4    관악구  2109  149.290780  520040  501957  18083  72249  3.477233  13.892970
21   은평구  2108   85.237258  487666  483197   4469  77420  0.916406  15.875620
20   용산구  2096   53.216374  245090  228999  16091  37640  6.565343  15.357624
6    구로구  1884   64.973730  438486  404497  33989  61801  7.751445  14.094179
10  동대문구  1870   74.766355  364338  348052  16286  57165  4.470025  15.690101
16   성북구  1651   63.627354  447687  435868  11819  67782  2.640014  15.140489
22   종로구  1619  248.922414  163026  153065   9961  26742  6.110068  16.403518
8    노원구  1566  188.929889  548160  543752   4408  77096  0.804145  14.064507
7    금천구  1348  100.000000  254021  233917  20104  35739  7.914306  14.069309
15   성동구  1327   81.780822  316463  308221   8242  42767  2.604412  13.514060
11   동작구  1302  139.338235  409385  396203  13182  59479  3.219952  14.528866
19  영등포구  1277  157.979798  403600  367778  35822  55673  8.875619  13.794103
13  서대문구  1254   48.578199  323080  310313  12767  50456  3.951653  15.617185
17   송파구  1081  104.347826  673507  666635   6872  81364  1.020331  12.080647
23    중구  1023  147.699758  135633  125725   9908  22005  7.305007  16.223928
1    강동구  1010  166.490765  431920  427573   4347  58770  1.006436  13.606686
12   마포구   980  212.101911  386359  375077  11282  50833  2.920082  13.156934
24   중랑구   916   79.960707  408147  403209   4938  61830  1.209858  15.148954
3    강서구   911  134.793814  603611  596949   6662  79660  1.103691  13.197241
5    광진구   878   53.228621  371063  355559  15504  45619  4.178266  12.294139
2    강북구   831  125.203252  322915  319164   3751  58196  1.161606  18.022080
9    도봉구   825  246.638655  341649  339413   2236  55964  0.654473  16.380554